#: kivy 1.9.1

<Menu>:
    GridLayout:
        cols: 3
        size: root.size
        pos: root.pos
        padding: 50, 90
        spacing: 20, 30
            
        Button:
            text: "Clock"
            background_color: (0.7, 0, 0, 1)
            background_normal: ''
            on_release: root.clock_btn()
            
        Button:
            text: "Timer"
            background_color: (0, 0.7, 0, 1)
            background_normal: ''
            on_release: root.timer_btn()
            
        Button:
            text: "Weather"
            background_color: (0, 0, 0.7, 1)
            background_normal: ''
            on_release: root.weather_btn()
            
        Button:
            text: "Calendar"
            background_color: (0.7, 0.7, 0, 1)
            background_normal: ''
            on_release: root.calendar_btn()
            
        Button:
            text: "Preferences"
            background_color: (0, 0.7, 0.7, 1)
            background_normal: ''
            on_release: root.preferences_btn()
            
        Button:
            text: "Desktop"
            background_color: (0.7, 0, 0.7, 1)
            background_normal: ''
            on_release: root.desktop_btn()