#: kivy 1.9.1

<Clock>:
    size: root.size
    BoxLayout:
        size_hint: (None, None)
        size: (500, 160)
        pos_hint: { 'center_x':0.5, 'center_y': 0.5}
        orientation: 'vertical'
        spacing: 50
        
        Label:
            size_hint: (None, None)
            size: (500, 160)
            text: root.current_time
            font_size: 200

        Label:
            text: root.current_date
            font_size: 40
